package io.github.amitelia.occultech.items;

import io.github.amitelia.occultech.pack.ResourcePackService;
import io.github.thebusybiscuit.slimefun4.api.events.SlimefunBlockPlaceEvent;
import io.github.thebusybiscuit.slimefun4.api.items.SlimefunItem;
import me.mrCookieSlime.Slimefun.api.BlockStorage;
import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.block.Block;
import org.bukkit.block.BlockFace;
import org.bukkit.block.data.BlockData;
import org.bukkit.block.data.Directional;
import org.bukkit.block.data.type.NoteBlock;
import org.bukkit.configuration.file.YamlConfiguration;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.Listener;
import org.bukkit.event.block.Action;
import org.bukkit.event.block.BlockFromToEvent;
import org.bukkit.event.block.BlockPhysicsEvent;
import org.bukkit.event.block.BlockPlaceEvent;
import org.bukkit.event.block.NotePlayEvent;
import org.bukkit.event.inventory.InventoryOpenEvent;
import org.bukkit.event.player.PlayerInteractEvent;
import org.bukkit.event.player.PlayerJoinEvent;
import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.BlockDataMeta;
import org.bukkit.plugin.java.JavaPlugin;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import java.io.File;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

/**
 * Occultech's blocks as real custom blocks, the way Nexo makes them (Session N). Each block look owns a vanilla block
 * state set aside for it - a powered note block (Nexo's NOTEBLOCK type) for blocks that fill their cube, a chorus plant
 * with neither up nor down (Nexo's CHORUSBLOCK type) for smaller models (a note block is a solid cube to the client,
 * which hides every touching block's face - through a smaller model you'd see the sky), a disarmed tripwire (Nexo's
 * STRINGBLOCK type) for the flat, walk-through ritual glyphs - and Occultech's resource pack shows the block's model for
 * that state. They are real blocks: they appear and vanish with the block, render at full distance, cost no entity.
 *
 * <p>The states come from {@code occultech-pack-blocks.txt} (generated by tools/art/build_pack.py; a state never
 * changes once given out, since placed blocks are stored as it). A placed block is still Slimefun's: Slimefun keeps its
 * id, data and menu by location exactly as before; only the vanilla block under it changed.
 *
 * <p>This is the only place that knows how a look is stored. On the Nexo server it becomes a call into Nexo's API
 * ({@code NexoBlocks.place}), and {@code /occultech blocks convert} re-places existing blocks - see
 * docs/nexo-migration.md.
 *
 * <p>No blink on placing: with custom blocks on, a block's item is made of a note block (string for the glyphs) carrying
 * its look's state, so the game's own placement prediction draws the custom block at once - not the item's vanilla block
 * for a moment until the server's answer arrives. A look smaller than a cube (a chorus-plant state, which can't be placed
 * freely) is predicted as a note-block state set aside to show the same model, and turned into its chorus state on the
 * server. A block with a front (the Occult Forge) carries the facing its holder looks along, kept up to date while held.
 * The block's own vanilla block (recipes.yml {@code material}) stays known to the code ({@link #vanillaMaterial}).
 *
 * <p>Like Nexo, it needs Paper's {@code block-updates.disable-noteblock-updates}, {@code disable-chorus-plant-updates} and
 * {@code disable-tripwire-updates}
 * (config/paper-global.yml): otherwise a neighbour or redstone could change a block's state, and so its look. It warns
 * at startup when they are off.
 */
public final class CustomBlockService implements Listener {

    /**
     * A placed custom block's look: its recipes.yml item id, which look (glyph variants, tile looks), its front. Not
     * {@code current}: a retired state (the block's kind changed) - the block is converted to its current state.
     */
    public record Look(String itemId, int look, @Nullable BlockFace facing, boolean current) {}

    private final JavaPlugin plugin;
    private final ResourcePackService pack;
    private final Map<String, BlockData> states = new HashMap<>();      // "ITEM look facing" -> its state
    private final Map<String, Look> byState = new HashMap<>();          // state (as the server prints it) -> look
    private final Map<String, Integer> looks = new HashMap<>();         // ITEM -> how many looks
    private final Set<String> directional = new HashSet<>();
    /** "ITEM look facing" -> a note-block state the client can predict, showing a chorus look's model (see the class doc). */
    private final Map<String, BlockData> predicted = new HashMap<>();
    /** Slimefun id -> its own vanilla block, for the items made of a note block or string here. */
    private static final Map<String, Material> VANILLA = new HashMap<>();
    private boolean enabled;

    public CustomBlockService(@Nonnull JavaPlugin plugin, @Nonnull ResourcePackService pack) {
        this.plugin = plugin;
        this.pack = pack;
    }

    /**
     * Reads the states and decides the mode ({@code custom-blocks.mode}: auto, blocks or skins). Auto uses custom blocks
     * unless Nexo is installed: there Nexo owns the note-block and tripwire states, so until the Nexo hookup is done
     * (docs/nexo-migration.md) blocks keep their display skins.
     */
    public void start() {
        for (String[] line : pack.customBlockLines()) {
            String key = line[0] + " " + line[1] + " " + line[2];
            boolean retired = line[1].equals("~");
            BlockData data;
            try {
                data = Bukkit.createBlockData(line[3]);
            } catch (IllegalArgumentException e) {
                plugin.getLogger().warning("Custom blocks: bad state for " + key + ": " + line[3]);
                continue;
            }
            BlockFace facing = line[2].equals("-") ? null : BlockFace.valueOf(line[2].toUpperCase(Locale.ROOT));
            if (line[1].startsWith("^")) {   // a prediction state: shows the look, converted to its real state once placed
                predicted.put(line[0] + " " + line[1].substring(1) + " " + line[2], data);
                byState.put(data.getAsString(), new Look(line[0], Integer.parseInt(line[1].substring(1)), facing, false));
                continue;
            }
            if (retired) {
                byState.put(data.getAsString(), new Look(line[0], 0, null, false));
                continue;
            }
            states.put(key, data);
            byState.put(data.getAsString(), new Look(line[0], Integer.parseInt(line[1]), facing, true));
            looks.merge(line[0], Integer.parseInt(line[1]) + 1, Math::max);
            if (facing != null) {
                directional.add(line[0]);
            }
        }
        String wanted = plugin.getConfig().getString("custom-blocks.mode", "auto").toLowerCase(Locale.ROOT);
        boolean nexo = Bukkit.getPluginManager().getPlugin("Nexo") != null;
        enabled = !states.isEmpty() && (wanted.equals("blocks") || (wanted.equals("auto") && !nexo));
        if (!enabled) {
            plugin.getLogger().info("Custom blocks: off (" + (states.isEmpty() ? "no states in the pack" : nexo && wanted.equals("auto")
                ? "Nexo is installed - blocks keep their display skins until the Nexo hookup, docs/nexo-migration.md" : "mode " + wanted) + ").");
            return;
        }
        Bukkit.getPluginManager().registerEvents(this, plugin);
        Bukkit.getScheduler().runTaskTimer(plugin, this::faceHeld, 4L, 4L);
        plugin.getLogger().info("Custom blocks: " + looks.size() + " blocks, " + states.size() + " states.");
        warnAboutBlockUpdates();
    }

    /** Whether Occultech's blocks are custom blocks here (false: display skins). */
    public boolean enabled() {
        return enabled;
    }

    /** A block's own vanilla block (its recipes.yml material), even when its item is made of a note block or string. */
    public static Material vanillaMaterial(@Nonnull SlimefunItem item) {
        return VANILLA.getOrDefault(item.getId(), item.getItem().getType());
    }

    /**
     * The state a custom block's item carries so the game predicts the custom block on placing it (its first look; a
     * front facing {@code facing}, north if null), or null if the item stays as it is.
     */
    @Nullable
    public BlockData placedState(@Nonnull String slimefunId, @Nullable BlockFace facing) {
        if (!isCustom(slimefunId)) {
            return null;
        }
        String item = BlockSkinService.stripPrefix(slimefunId);
        String key = item + " 0 " + (directional.contains(item) ? (facing == null ? BlockFace.NORTH : facing).name().toLowerCase(Locale.ROOT) : "-");
        BlockData data = predicted.getOrDefault(key, states.get(key));
        return data == null || data.getMaterial() == Material.CHORUS_PLANT ? null : data;
    }

    /**
     * Registration: the material a custom block's item is made of (a note block, or string for a tripwire look), or
     * {@code own} if it stays as it is. Remembers {@code own} as the block's vanilla block.
     */
    public Material itemMaterial(@Nonnull String slimefunId, @Nonnull Material own) {
        BlockData data = placedState(slimefunId, null);
        if (data == null) {
            return own;
        }
        VANILLA.put(slimefunId, own);
        return data.getMaterial() == Material.TRIPWIRE ? Material.STRING : data.getMaterial();
    }

    /** Puts the predicted state on a custom block's item (see {@link #placedState}); false if nothing changed. */
    public boolean carryState(@Nullable ItemStack item, @Nullable BlockFace facing) {
        SlimefunItem sf = item == null || item.getType().isAir() ? null : SlimefunItem.getByItem(item);
        return sf != null && carryState(item, sf.getId(), facing);
    }

    /** The same, by id (registration: the item isn't registered yet). */
    public boolean carryState(@Nonnull ItemStack item, @Nonnull String slimefunId, @Nullable BlockFace facing) {
        BlockData data = placedState(slimefunId, facing);
        if (data == null || !(item.getItemMeta() instanceof BlockDataMeta meta)) {
            return false;
        }
        BlockData now = meta.hasBlockData() ? meta.getBlockData(item.getType() == Material.STRING ? Material.TRIPWIRE : item.getType()) : null;
        if (now != null && now.matches(data)) {
            return false;
        }
        meta.setBlockData(data);
        item.setItemMeta(meta);
        return true;
    }

    /**
     * A custom block's item from before this (made of its vanilla block): made of a note block or string now, carrying
     * its state, so it stacks with new ones and places without a blink. Returns the converted item, or null if it was fine.
     */
    @Nullable
    public ItemStack upgrade(@Nullable ItemStack item) {
        SlimefunItem sf = item == null || item.getType().isAir() ? null : SlimefunItem.getByItem(item);
        if (sf == null || !isCustom(sf.getId()) || item.getType() == sf.getItem().getType()) {
            return null;
        }
        Material target = sf.getItem().getType();
        if (target != Material.NOTE_BLOCK && target != Material.STRING) {
            return null;
        }
        ItemStack fresh = item.withType(target);
        carryState(fresh, sf.getId(), null);
        return fresh;
    }

    private void upgradeAll(Inventory inventory) {
        ItemStack[] contents = inventory.getContents();
        for (int i = 0; i < contents.length; i++) {
            ItemStack fresh = upgrade(contents[i]);
            if (fresh != null) {
                inventory.setItem(i, fresh);
            }
        }
    }

    @EventHandler
    public void onJoin(PlayerJoinEvent event) {
        upgradeAll(event.getPlayer().getInventory());
        upgradeAll(event.getPlayer().getEnderChest());
    }

    @EventHandler(ignoreCancelled = true)
    public void onOpen(InventoryOpenEvent event) {
        upgradeAll(event.getInventory());
        upgradeAll(event.getPlayer().getInventory());
    }

    /** A held block with a front carries the facing its holder looks along, so it's predicted facing the right way. */
    private void faceHeld() {
        if (directional.isEmpty()) {
            return;
        }
        for (org.bukkit.entity.Player player : Bukkit.getOnlinePlayers()) {
            BlockFace facing = player.getFacing().getOppositeFace();
            for (ItemStack held : new ItemStack[] { player.getInventory().getItemInMainHand(), player.getInventory().getItemInOffHand() }) {
                SlimefunItem sf = held.getType().isAir() ? null : SlimefunItem.getByItem(held);
                if (sf != null && directional.contains(BlockSkinService.stripPrefix(sf.getId()))) {
                    carryState(held, facing);   // the held stack itself: the change reaches the client with the next sync
                }
            }
        }
    }

    /** Whether this Slimefun id is a custom block. */
    public boolean isCustom(@Nullable String slimefunId) {
        return enabled && slimefunId != null && looks.containsKey(BlockSkinService.stripPrefix(slimefunId));
    }

    /** How many looks a block has (glyph variants, a tile's looks); 0 if it isn't a custom block. */
    public int looks(@Nonnull String slimefunId) {
        return looks.getOrDefault(BlockSkinService.stripPrefix(slimefunId), 0);
    }

    /** The look a block shows, or null if its state isn't one of ours. */
    @Nullable
    public Look lookOf(@Nonnull Block block) {
        Material type = block.getType();
        if (type != Material.NOTE_BLOCK && type != Material.TRIPWIRE && type != Material.CHORUS_PLANT) {
            return null;
        }
        return byState.get(block.getBlockData().getAsString());
    }

    /** Whether this block shows one of Occultech's custom-block states. */
    public boolean isCustomState(@Nonnull Block block) {
        return lookOf(block) != null;
    }

    /**
     * Sets the block to the state of this look (no physics, so nothing around reacts). A block with a front faces
     * {@code facing} (north if null). Returns false if there's no such look.
     */
    public boolean place(@Nonnull Block block, @Nonnull String slimefunId, int look, @Nullable BlockFace facing) {
        String item = BlockSkinService.stripPrefix(slimefunId);
        String side = directional.contains(item) ? (facing == null ? BlockFace.NORTH : facing).name().toLowerCase(Locale.ROOT) : "-";
        BlockData data = states.get(item + " " + look + " " + side);
        if (data == null) {
            return false;
        }
        block.setBlockData(data, false);
        return true;
    }

    /**
     * Makes a placed Occultech block show its custom block if it doesn't yet - a block placed from code, an altar that
     * just upgraded, or a block from before custom blocks (its look is read from its vanilla block: a tile's block, a
     * front's facing; a glyph's variant by position, as its skin had it).
     */
    public void ensure(@Nonnull Block block, @Nullable String slimefunId) {
        if (!isCustom(slimefunId)) {
            return;
        }
        String item = BlockSkinService.stripPrefix(slimefunId);
        Look now = lookOf(block);
        if (now != null && now.itemId().equals(item) && now.current()) {
            return;
        }
        int look = 0;
        int count = looks.get(item);
        if (SlimefunItem.getById(slimefunId) instanceof StepTile tile) {
            look = Math.max(0, tile.lookVariant(block.getType()));
        } else if (count > 1) {
            look = positionLook(block, count);
        }
        BlockFace facing = block.getBlockData() instanceof Directional d && d.getFacing().isCartesian()
            && d.getFacing().getModY() == 0 ? d.getFacing() : null;
        place(block, slimefunId, look, facing);
    }

    /** A block with several looks and no choice of its own (glyphs) picks one by position, so a circle looks varied. */
    public static int positionLook(@Nonnull Block block, int count) {
        return Math.floorMod(block.getX() * 31 + block.getZ() * 17 + block.getY() * 7, count);
    }

    /**
     * A player placed an Occultech block: it becomes its custom block in the same tick. Usually it already is - the item
     * carried the state and the client predicted it - so only a chorus look (predicted as a note block) or a glyph's
     * variant by position changes it; a front keeps the facing it was placed with.
     */
    @EventHandler(priority = EventPriority.MONITOR, ignoreCancelled = true)
    public void onPlace(BlockPlaceEvent event) {
        SlimefunItem item = SlimefunItem.getByItem(event.getItemInHand());
        if (item != null && isCustom(item.getId())) {
            String id = BlockSkinService.stripPrefix(item.getId());
            Block block = event.getBlockPlaced();
            int look = looks.get(id) > 1 && !(item instanceof StepTile) ? positionLook(block, looks.get(id)) : 0;
            Look now = lookOf(block);
            BlockFace facing = now != null && now.itemId().equals(id) && now.facing() != null ? now.facing()
                : event.getPlayer().getFacing().getOppositeFace();
            if (now != null && now.current() && now.itemId().equals(id) && now.look() == look) {
                return;   // predicted exactly
            }
            place(block, item.getId(), look, facing);
        } else if (item == null && event.getBlockPlaced().getType() == Material.NOTE_BLOCK && isCustomState(event.getBlockPlaced())) {
            unpower(event.getBlockPlaced());   // a plain note block placed next to power must not look like one of ours
        }
    }

    /** Slimefun placed one (a block placer, or after a player's placement): same, idempotent. */
    @EventHandler(priority = EventPriority.MONITOR, ignoreCancelled = true)
    public void onSlimefunPlace(SlimefunBlockPlaceEvent event) {
        ensure(event.getBlockPlaced(), event.getSlimefunItem().getId());
    }

    /**
     * Right-clicking one of our note blocks must not tune it (that would change its state, and so its look). Sneaking with
     * something in hand skips the block, as vanilla does - so blocks can be placed against ours. (Denying the block
     * there too made the click do nothing: nothing could be stacked on an Occultech block.)
     */
    @EventHandler(priority = EventPriority.HIGHEST)
    public void onInteract(PlayerInteractEvent event) {
        Block block = event.getClickedBlock();
        Look look = block == null ? null : lookOf(block);
        if (look != null && !look.current()) {   // a retired state: convert the block now that someone uses it
            ensure(block, io.github.amitelia.occultech.content.ItemKeys.slimefunId(look.itemId()));
        }
        if (event.getAction() == Action.RIGHT_CLICK_BLOCK && block != null && block.getType() == Material.NOTE_BLOCK) {
            boolean placing = event.getPlayer().isSneaking() && event.getItem() != null && !event.getItem().getType().isAir();
            if (isCustomState(block) && !placing) {
                event.setUseInteractedBlock(org.bukkit.event.Event.Result.DENY);
            } else if (BlockStorage.checkID(block) == null) {
                // a plain note block that a tune could carry into one of our states
                Bukkit.getScheduler().runTask(plugin, () -> {
                    if (isCustomState(block) && BlockStorage.checkID(block) == null) {
                        unpower(block);
                    }
                });
            }
        }
    }

    /** Our note blocks are silent (a hit would play a note). */
    @EventHandler(priority = EventPriority.HIGH, ignoreCancelled = true)
    public void onNote(NotePlayEvent event) {
        if (isCustomState(event.getBlock())) {
            event.setCancelled(true);
        }
    }

    /** A neighbour change must not update one of our blocks (Paper's setting does this too; this is the backstop). */
    @EventHandler(priority = EventPriority.HIGH, ignoreCancelled = true)
    public void onPhysics(BlockPhysicsEvent event) {
        Material type = event.getBlock().getType();
        if ((type == Material.NOTE_BLOCK || type == Material.TRIPWIRE || type == Material.CHORUS_PLANT) && isCustomState(event.getBlock())) {
            event.setCancelled(true);
        }
    }

    /** Water must not wash a glyph away. */
    @EventHandler(priority = EventPriority.HIGH, ignoreCancelled = true)
    public void onFlow(BlockFromToEvent event) {
        if (event.getToBlock().getType() == Material.TRIPWIRE && isCustomState(event.getToBlock())) {
            event.setCancelled(true);
        }
    }

    private static void unpower(Block block) {
        if (block.getBlockData() instanceof NoteBlock note) {
            note.setPowered(false);
            block.setBlockData(note, false);
        }
    }

    private void warnAboutBlockUpdates() {
        File file = new File(Bukkit.getWorldContainer(), "config/paper-global.yml");
        if (!file.exists()) {
            return;
        }
        YamlConfiguration paper = YamlConfiguration.loadConfiguration(file);
        if (!paper.getBoolean("block-updates.disable-noteblock-updates") || !paper.getBoolean("block-updates.disable-tripwire-updates")
            || !paper.getBoolean("block-updates.disable-chorus-plant-updates")) {
            plugin.getLogger().warning("Custom blocks: set block-updates.disable-noteblock-updates, disable-chorus-plant-updates and"
                + " disable-tripwire-updates to true"
                + " in config/paper-global.yml (as Nexo also needs) - otherwise redstone or a neighbour can change a block's look.");
        }
    }
}
